##
##  Makefile -- Build procedure for sample hmacauth Apache module
##  Autogenerated via ``apxs -n hmacauth -g''.
##

builddir=.
top_srcdir=/opt/apache
top_builddir=/opt/apache
include /opt/apache/build/special.mk

#   the used tools
APXS=apxs
APACHECTL=apachectl

#   additional defines, includes and libraries
#DEFS=-Dmy_define=my_value
#INCLUDES=-Imy/include/dir
#LIBS=-Lmy/lib/dir -lmylib

#   the default target
all: local-shared-build

#   install the shared object file into Apache 
install: install-modules-yes

#   cleanup
clean:
	-rm -f mod_hmacauth.o mod_hmacauth.lo mod_hmacauth.slo mod_hmacauth.la 

#   simple test
test: reload
	lynx -mime_header http://localhost/hmacauth

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

